# Generated by Django 4.2.10 on 2024-02-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_hide_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('P', 'Pinky'), ('F', 'Fuzzy'), ('H', 'Hopper')], default='P', max_length=1),
        ),
    ]
