# Generated by Django 4.2.10 on 2024-03-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_feeding_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='hides',
            field=models.ManyToManyField(to='main_app.hide'),
        ),
    ]
